persistence true
persistence_location /mosquitto/data/

# Log to stdout (avoid volume permission issues)
log_dest stdout

allow_anonymous false
password_file /mosquitto/config/passwordfile

# Setze den Port und andere notwendige Konfigurationen
port 1883
listener 9001
protocol websockets
